# Generated by Django 3.2.13 on 2022-06-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='available_bitcoin',
            field=models.FloatField(default=4.246892495188323),
        ),
    ]
