# Generated by Django 2.2.24 on 2022-05-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220516_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='available_bitcoin',
            field=models.FloatField(default=4.360310476057329),
        ),
    ]
