# Generated by Django 2.2.24 on 2022-05-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220518_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='available_bitcoin',
            field=models.FloatField(default=7.892496741316405),
        ),
    ]
